-- Kitchen Craft PK — 75 products.
-- Schema chalane ke baad yeh file SQL Editor mein run karein.
insert into public.products (sku, name, sub, cat, price, specs) values
  ('CW-01', 'Non-Stick Karahi 30cm', 'Three-layer marble coating, works on gas and induction', 'cookware', 4200, '["Marble non-stick", "30cm, dhakkan alag"]'::jsonb),
  ('CW-02', 'Non-Stick Karahi 26cm', 'Everyday size with a wooden grip handle', 'cookware', 3400, '["Marble non-stick", "26cm, wooden handle"]'::jsonb),
  ('CW-03', 'Steel Degchi 5 Litre', 'Heavy gauge body with a fitted steel lid', 'cookware', 5600, '["Stainless steel", "5 litre, lid included"]'::jsonb),
  ('CW-04', 'Aluminium Pateeli 7 Litre', 'Deep pot sized for biryani and daal', 'cookware', 3900, '["Heavy aluminium", "7 litre, do handle"]'::jsonb),
  ('CW-05', 'Pressure Cooker 5 Litre', 'Safety valve with a locking lid', 'cookware', 7800, '["Aluminium body", "5 litre, safety valve"]'::jsonb),
  ('CW-06', 'Roti Tawa 30cm', 'Thick base that spreads heat evenly', 'cookware', 1900, '["Iron, thick base", "30cm, roti ke liye"]'::jsonb),
  ('CW-07', 'Cast Iron Tawa 26cm', 'Pre-seasoned and holds heat for a long time', 'cookware', 3200, '["Cast iron", "26cm, pre-seasoned"]'::jsonb),
  ('CW-08', 'Non-Stick Fry Pan 24cm', 'Low sides and one handle, easy for anda', 'cookware', 2600, '["Non-stick coating", "24cm, single handle"]'::jsonb),
  ('CW-09', 'Steel Wok 32cm with Lid', 'Double handle and a tempered glass lid', 'cookware', 8300, '["Stainless steel", "32cm, glass lid"]'::jsonb),
  ('CW-10', 'Milk Pan 1.5 Litre', 'Pouring lip and a rim that stops boil-over', 'cookware', 1450, '["Non-stick", "1.5 litre, pouring lip"]'::jsonb),
  ('CW-11', 'Three-Tier Steamer Pot', 'Stacked trays for kebab, momos and vegetables', 'cookware', 6100, '["Steel, 3 tier", "24cm, steam trays"]'::jsonb),
  ('CW-12', 'Grill Pan 28cm', 'Ridged base that leaves bar-b-q marks', 'cookware', 4700, '["Non-stick ridged", "28cm, grill marks"]'::jsonb),
  ('KT-01', 'Steel Chimta 12 inch', 'Flat tongs for roti straight off the tawa', 'tools', 450, '["Stainless steel", "12 inch, flat jaw"]'::jsonb),
  ('KT-02', 'Slotted Palta', 'Turner shaped for anda and paratha', 'tools', 520, '["Steel, slotted", "Wooden grip handle"]'::jsonb),
  ('KT-03', 'Serving Ladle', 'Deep bowl that pours daal and salan cleanly', 'tools', 620, '["Stainless steel", "8oz deep bowl"]'::jsonb),
  ('KT-04', 'Skimmer Spoon', 'Lifts pakoras out of hot oil and drains them', 'tools', 560, '["Steel mesh", "Oil drain design"]'::jsonb),
  ('KT-05', 'Balloon Whisk', 'Stainless wire for eggs and cream', 'tools', 690, '["Steel wire", "10 inch balloon"]'::jsonb),
  ('KT-06', 'Vegetable Peeler', 'Swivel blade with a soft grip handle', 'tools', 380, '["Steel blade", "Swivel, soft grip"]'::jsonb),
  ('KT-07', 'Four-Side Grater', 'Cheese, carrot, adrak and lemon zest on one tool', 'tools', 980, '["Steel, 4 sides", "Non-slip base"]'::jsonb),
  ('KT-08', 'Potato Masher', 'Wide steel plate for aloo bhurta', 'tools', 640, '["Steel plate", "Wide head masher"]'::jsonb),
  ('KT-09', 'Wooden Belan', 'Smooth roller that does not stick to atta', 'tools', 450, '["Seasoned wood", "9 inch roller"]'::jsonb),
  ('KT-10', 'Marble Chakla 10 inch', 'Cool surface, keeps dough from sticking', 'tools', 2200, '["Marble slab", "10 inch, wooden stand"]'::jsonb),
  ('KT-11', 'Garlic Press', 'Crushes lehsan with the skin still on', 'tools', 890, '["Zinc alloy", "Dishwasher safe"]'::jsonb),
  ('KT-12', 'Kitchen Scissors', 'Cuts through chicken joints and packaging', 'tools', 750, '["Steel blades", "Soft grip handle"]'::jsonb),
  ('KT-13', 'Measuring Spoon Set', 'Five sizes held together on one ring', 'tools', 420, '["Stainless steel", "5 sizes, one ring"]'::jsonb),
  ('KT-14', 'Measuring Cup Set', 'Four nesting cups marked in cups and ml', 'tools', 560, '["Stainless steel", "4 nesting cups"]'::jsonb),
  ('KT-15', 'Steel Channi 22cm', 'Fine mesh for chai, atta and rice', 'tools', 680, '["Steel fine mesh", "22cm, hook handle"]'::jsonb),
  ('KN-01', 'Chef Knife 8 inch', 'Forged blade balanced for daily prep', 'cutlery', 2400, '["Forged steel", "8 inch blade"]'::jsonb),
  ('KN-02', 'Paring Knife 3.5 inch', 'Short blade for peeling and trimming', 'cutlery', 750, '["Stainless steel", "3.5 inch blade"]'::jsonb),
  ('KN-03', 'Bread Knife 8 inch', 'Serrated edge that slices without tearing', 'cutlery', 1650, '["Serrated steel", "8 inch blade"]'::jsonb),
  ('KN-04', 'Knife Set of Five', 'Comes with a magnetic wooden block', 'cutlery', 6900, '["Steel, 5 knives", "Magnetic wood block"]'::jsonb),
  ('KN-05', 'Meat Cleaver', 'Heavy blade for bone-in cuts', 'cutlery', 2900, '["Heavy carbon steel", "Bone-in cutting"]'::jsonb),
  ('KN-06', 'Bamboo Cutting Board', 'Juice groove on both faces', 'cutlery', 1800, '["Bamboo", "Juice groove, 2 sides"]'::jsonb),
  ('KN-07', 'Chopping Board Set of Three', 'Colour coded so meat and sabzi stay apart', 'cutlery', 1350, '["Food-grade plastic", "3 boards, colour coded"]'::jsonb),
  ('KN-08', 'Knife Sharpener', 'Two stages, carbide then ceramic', 'cutlery', 890, '["Carbide + ceramic", "Non-slip base"]'::jsonb),
  ('KN-09', 'Manual Vegetable Chopper', 'Pull cord chops pyaz in a few seconds', 'cutlery', 1950, '["Plastic + steel", "900ml bowl, pull cord"]'::jsonb),
  ('ST-01', 'Air-Tight Jar Set of Six', 'Clear jars with clip lids and rubber seals', 'storage', 3200, '["Clear plastic", "6 jars, clip lids"]'::jsonb),
  ('ST-02', 'Masala Rack of Twelve', 'Rotating stand with small steel spoons', 'storage', 2800, '["Steel + acrylic", "12 jars, rotating"]'::jsonb),
  ('ST-03', 'Atta Container 10kg', 'Wide mouth with a scoop inside', 'storage', 2100, '["Food-grade plastic", "10kg, scoop included"]'::jsonb),
  ('ST-04', 'Steel Lunch Box, Three Tier', 'Insulated body with a carry bag', 'storage', 2450, '["Steel, insulated", "3 tier, carry bag"]'::jsonb),
  ('ST-05', 'Steel Water Bottle 1 Litre', 'Stays cold for about eight hours', 'storage', 1600, '["Steel, vacuum", "1 litre, leak proof"]'::jsonb),
  ('ST-06', 'Hot Pot 3 Litre', 'Keeps salan warm through dinner', 'storage', 2900, '["Steel + PU foam", "3 litre, roti case"]'::jsonb),
  ('ST-07', 'Roti Hot Case 25cm', 'Holds a dozen rotis and keeps them soft', 'storage', 1750, '["Steel inner", "25cm, keeps soft"]'::jsonb),
  ('ST-08', 'Fridge Bottle Set of Four', 'One litre each, fits the fridge door', 'storage', 1250, '["BPA-free plastic", "4 bottles, 1 litre"]'::jsonb),
  ('ST-09', 'Cling Film Cutter Box', 'Slide cutter so the film never tangles', 'storage', 690, '["Plastic box", "Slide cutter, 30m"]'::jsonb),
  ('ST-10', 'Bread Bin with Lid', 'Keeps bread and rusk fresh on the counter', 'storage', 1900, '["Steel with lid", "Bread aur rusk"]'::jsonb),
  ('SV-01', 'Dinner Set of 32 Pieces', 'Service for six in chip-resistant porcelain', 'serving', 11500, '["Porcelain", "32 pieces, 6 log"]'::jsonb),
  ('SV-02', 'Tea Set of Twelve', 'Six cups with matching saucers', 'serving', 4200, '["Porcelain", "12 pieces, gold rim"]'::jsonb),
  ('SV-03', 'Melamine Bowl Set of Six', 'Sized for salan, raita and salad', 'serving', 1800, '["Melamine", "6 bowls, medium"]'::jsonb),
  ('SV-04', 'Glass Set of Six', 'Straight sided, 300ml each', 'serving', 1400, '["Tempered glass", "6 glass, 300ml"]'::jsonb),
  ('SV-05', 'Serving Tray 16 inch', 'Steel rim with a non-slip base', 'serving', 1650, '["Steel rim tray", "16 inch, anti-slip"]'::jsonb),
  ('SV-06', 'Water Jug 2 Litre', 'Lid strains pulp when you pour', 'serving', 1350, '["Acrylic", "2 litre, filter lid"]'::jsonb),
  ('SV-07', 'Thermos Flask 1 Litre', 'Chai stays hot from asr to maghrib', 'serving', 2600, '["Steel, vacuum", "1 litre, 12 ghante"]'::jsonb),
  ('SV-08', 'Cutlery Set of 24 Pieces', 'Spoons, forks and knives for six people', 'serving', 3400, '["Stainless steel", "24 pieces, 6 log"]'::jsonb),
  ('SV-09', 'Roti Basket with Cloth', 'Cane weave that holds a full stack', 'serving', 950, '["Cane weave", "With cotton cloth"]'::jsonb),
  ('BK-01', 'Baking Tray 12 inch', 'Non-stick sheet for biscuits and cake', 'bake', 1450, '["Non-stick steel", "12 inch tray"]'::jsonb),
  ('BK-02', 'Round Cake Mould 9 inch', 'Loose base lifts the cake out whole', 'bake', 1250, '["Non-stick steel", "9 inch, loose base"]'::jsonb),
  ('BK-03', 'Muffin Tray of Twelve', 'Works for cupcakes and kebab bites', 'bake', 1550, '["Non-stick steel", "12 cups"]'::jsonb),
  ('BK-04', 'Silicone Spatula Set of Three', 'Heat safe up to 240 degrees', 'bake', 1100, '["Silicone + steel", "3 pieces, 240C"]'::jsonb),
  ('BK-05', 'Pastry Brush', 'Silicone bristles for a ghee wash', 'bake', 480, '["Silicone bristles", "Heat safe handle"]'::jsonb),
  ('BK-06', 'Piping Bag and Nozzle Set', 'Twelve tips for icing and cream', 'bake', 1600, '["Nylon bag + steel", "12 nozzles"]'::jsonb),
  ('BK-07', 'Cooling Rack 40cm', 'Raised grid keeps the base from going soft', 'bake', 950, '["Chrome steel", "40cm grid"]'::jsonb),
  ('AP-01', 'Hand Blender 700W', 'Blends soup straight in the pot', 'appliance', 5400, '["700W motor", "Steel blending rod"]'::jsonb),
  ('AP-02', 'Electric Kettle 1.8 Litre', 'Steel body with auto cut-off', 'appliance', 3900, '["Steel body", "1.8 litre, auto cut-off"]'::jsonb),
  ('AP-03', 'Electric Chopper 400W', 'Pyaz, lehsan and mince in one jar', 'appliance', 4600, '["400W motor", "1.2L jar, steel blades"]'::jsonb),
  ('AP-04', 'Sandwich Maker', 'Non-stick plates with a ready light', 'appliance', 5200, '["Non-stick plates", "750W, ready light"]'::jsonb),
  ('AP-05', 'Egg Boiler, Seven Eggs', 'Three settings with a buzzer', 'appliance', 3300, '["7 egg capacity", "3 settings, buzzer"]'::jsonb),
  ('AP-06', 'Hand Mixer 300W', 'Five speeds with dough hooks included', 'appliance', 4800, '["300W motor", "5 speed, dough hooks"]'::jsonb),
  ('AP-07', 'Citrus Juicer 40W', 'Sized for malta and mausambi', 'appliance', 3600, '["40W motor", "Pulp filter included"]'::jsonb),
  ('CL-01', 'Two-Tier Dish Rack', 'Drip tray underneath and a cutlery holder', 'clean', 4200, '["Steel, 2 tier", "Drip tray included"]'::jsonb),
  ('CL-02', 'Sink Strainer Basket', 'Catches scraps before they block the pipe', 'clean', 520, '["Steel basket", "Standard sink size"]'::jsonb),
  ('CL-03', 'Scrub Pad Pack of Six', 'Rough side for degchi, soft side for non-stick', 'clean', 340, '["Foam + fibre", "6 pads, dono side"]'::jsonb),
  ('CL-04', 'Apron with Front Pocket', 'Cotton canvas with adjustable neck strap', 'clean', 1150, '["Cotton canvas", "Front pocket, adjustable"]'::jsonb),
  ('CL-05', 'Oven Gloves, Pair', 'Quilted cotton, safe for hot trays', 'clean', 890, '["Quilted cotton", "Pair, heat safe"]'::jsonb),
  ('CL-06', 'Steel Gas Lighter', 'Refillable with a long nozzle', 'clean', 420, '["Steel body", "Refillable, long nozzle"]'::jsonb)
on conflict (sku) do update set
  name = excluded.name, sub = excluded.sub, cat = excluded.cat,
  price = excluded.price, specs = excluded.specs;
