-- Kitchen Craft PK — Supabase schema
-- Supabase dashboard > SQL Editor mein yeh poori file paste kar ke "Run" dabayein.

create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  sku         text unique not null,
  name        text not null,
  sub         text,
  cat         text not null,
  price       integer not null,
  specs       jsonb not null default '[]'::jsonb,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.orders (
  id             bigint generated by default as identity primary key,
  customer_name  text not null,
  phone          text,
  city           text,
  address        text,
  note           text,
  total          integer not null default 0,
  items          jsonb not null default '[]'::jsonb,
  message        text,
  status         text not null default 'new',
  created_at     timestamptz not null default now()
);

-- Row Level Security: products sab parh sakte hain, orders sirf insert ho sakte hain.
alter table public.products enable row level security;
alter table public.orders   enable row level security;

drop policy if exists "products readable by everyone" on public.products;
create policy "products readable by everyone"
  on public.products for select
  to anon, authenticated
  using (active);

drop policy if exists "anyone can place an order" on public.orders;
create policy "anyone can place an order"
  on public.orders for insert
  to anon, authenticated
  with check (true);

-- NOTE: orders par koi select policy nahi hai, is liye website se orders parhe nahi ja sakte.
-- Aap khud Supabase dashboard (Table editor) mein orders dekhein.
